const products = [
  {
    _id: "1",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "90",
    rating: "4.5",
    countInStock: 55,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "iPhone 15 Pro Max 256GB",
    image: "/images/iphone.png",
    description:
      "Device that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "1200",
    rating: "4.5",
    countInStock: 22,
    numReviews: 22,
  },
  {
    _id: "3",
    name: "Camera",
    image: "/images/camera.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Canon EOS 800 DSLR Camera",
    category: "Electronics",
    price: "90",
    rating: "3.5",
    countInStock: 11,
    numReviews: 33,
  },
  {
    _id: "4",
    name: "Mouse",
    image: "/images/mouse.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "42",
    rating: "4",
    countInStock: 0,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "iPhone 11 Pro Max",
    image: "/images/phone.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "999",
    rating: "5",
    countInStock: 12,
    numReviews: 31,
  },
  {
    _id: "6",
    name: "PlayStation 5",
    image: "/images/playstation.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "90",
    rating: "5",
    countInStock: 0,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/sample.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "40",
    rating: "5",
    countInStock: 0,
    numReviews: 22,
  },
  {
    _id: "8",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.jpg",
    description:
      "Bluetooth Headphones that lets you connect it with compatible devices wirelessly",
    brand: "Apple",
    category: "Electronics",
    price: "30",
    rating: "5",
    countInStock: 22,
    numReviews: 32,
  },
];
export default products;
